### ISSUE TITLE
Add your name to the CONTRIBUTORS.md file

### ISSUE THREAD

**Issue by Abhey** [ContriHUB/ContriHUB.github.io#1]

**Comment by surbhitawasthi** [comment]
Added entry in CONTRIBUTORS.md fixes #43

**Comment by Aniket468** [comment]
Added Info in contributors.md file #63

**Comment by Aniket468** [comment]
[Added Aniket Kumar to the CONTRIBUTORS.md](https://github.com/ContriHUB/ContriHUB.github.io/pull/63) fixes #63

**Comment by Aniket468** [comment]
[Added Aniket Kumar to the CONTRIBUTORS.md](https://github.com/ContriHUB/ContriHUB.github.io/pull/63) fixes #63

**Comment by bhonesh1998** [comment]
Added bhonesh chawla to contributor.md #67
